name: hotels
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.2
  carousel_slider: ^4.2.1
  star_rating: ^0.11.0
  mask_text_input_formatter: ^2.5.0
  zoom_tap_animation: ^1.1.0
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/


  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic

